export let centr = [
  {
    "ID": "T81704",
    "Title": "Landing Screen Sanity",
    "Assigned To": "",
    "Case ID": "C19531",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Landing Screen",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Michael Powell",
    "Tested On": "7/04/2022 10:20 AM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81705",
    "Title": "Sign In Sanity",
    "Assigned To": "",
    "Case ID": "C19532",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Sign In",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Michael Powell",
    "Tested On": "7/04/2022 10:20 AM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81706",
    "Title": "Forgot Password",
    "Assigned To": "",
    "Case ID": "C19533",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Sign In",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Michael Powell",
    "Tested On": "7/04/2022 10:21 AM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81707",
    "Title": "Register Sanity",
    "Assigned To": "",
    "Case ID": "C19534",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Register",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Michael Powell",
    "Tested On": "7/04/2022 10:23 AM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81714",
    "Title": "Library Hamburger Menu Functionality",
    "Assigned To": "",
    "Case ID": "C19643",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Explore (Library)",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Le Phuong Thao",
    "Tested On": "7/04/2022 2:12 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81715",
    "Title": "Self-Guided Workouts",
    "Assigned To": "",
    "Case ID": "C19644",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Explore (Library)",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Le Phuong Thao",
    "Tested On": "7/04/2022 2:12 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81716",
    "Title": "Coached Workouts",
    "Assigned To": "",
    "Case ID": "C19645",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Explore (Library)",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Le Phuong Thao",
    "Tested On": "7/04/2022 2:12 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81717",
    "Title": "Recipes",
    "Assigned To": "",
    "Case ID": "C19646",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Explore (Library)",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Nguyen Xuan Ha Chi",
    "Tested On": "7/04/2022 1:11 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81718",
    "Title": "Snacks",
    "Assigned To": "",
    "Case ID": "C19647",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Explore (Library)",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Nguyen Xuan Ha Chi",
    "Tested On": "7/04/2022 12:48 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81719",
    "Title": "Meditation",
    "Assigned To": "",
    "Case ID": "C19648",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Explore (Library)",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Nguyen Xuan Ha Chi",
    "Tested On": "7/04/2022 12:51 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81720",
    "Title": "Features",
    "Assigned To": "",
    "Case ID": "C19649",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Explore (Library)",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Le Phuong Thao",
    "Tested On": "7/04/2022 2:05 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81721",
    "Title": "Verify all images in library and after opening activity from library are lazy loading",
    "Assigned To": "",
    "Case ID": "C19650",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Explore (Library)",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Le Phuong Thao",
    "Tested On": "7/04/2022 2:05 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81708",
    "Title": "Planner Sanity",
    "Assigned To": "",
    "Case ID": "C19535",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Planner",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Nguyen Xuan Ha Chi",
    "Tested On": "7/04/2022 12:15 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81713",
    "Title": "Program Sanity",
    "Assigned To": "",
    "Case ID": "C19642",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Programs",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Michael Powell",
    "Tested On": "7/04/2022 1:11 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81709",
    "Title": "Workouts Sanity",
    "Assigned To": "",
    "Case ID": "C19536",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Workouts",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Nguyen Xuan Ha Chi",
    "Tested On": "7/04/2022 2:05 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81710",
    "Title": "Recipe Sanity",
    "Assigned To": "",
    "Case ID": "C19537",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Recipe",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Nguyen Xuan Ha Chi",
    "Tested On": "7/04/2022 1:11 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81711",
    "Title": "Shopping List Sanity",
    "Assigned To": "",
    "Case ID": "C19538",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Shopping List",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Michael Powell",
    "Tested On": "7/04/2022 1:29 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81712",
    "Title": "Settings Sanity",
    "Assigned To": "",
    "Case ID": "C19539",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Settings",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Michael Powell",
    "Tested On": "7/04/2022 1:38 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81727",
    "Title": "Workout History",
    "Assigned To": "",
    "Case ID": "C38501",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "Medium",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Profile",
    "Section Depth": 1,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Michael Powell",
    "Tested On": "7/04/2022 1:45 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81722",
    "Title": "sitemap.xml",
    "Assigned To": "",
    "Case ID": "C29749",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "High",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Regression - Service App",
    "Section Depth": 0,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Nguyen Xuan Ha Chi",
    "Tested On": "7/04/2022 1:59 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81723",
    "Title": "robots.txt",
    "Assigned To": "",
    "Case ID": "C29750",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "High",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Regression - Service App",
    "Section Depth": 0,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Nguyen Xuan Ha Chi",
    "Tested On": "7/04/2022 1:17 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81724",
    "Title": "node.js",
    "Assigned To": "",
    "Case ID": "C29751",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "High",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Regression - Service App",
    "Section Depth": 0,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Le Phuong Thao",
    "Tested On": "7/04/2022 2:03 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81725",
    "Title": "Blog Articles",
    "Assigned To": "",
    "Case ID": "C29752",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "High",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Regression - Service App",
    "Section Depth": 0,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Nguyen Xuan Ha Chi",
    "Tested On": "7/04/2022 12:03 PM",
    "Type": "Other",
    "Version": ""
  },
  {
    "ID": "T81726",
    "Title": "Articles with an expired token or session",
    "Assigned To": "",
    "Case ID": "C29840",
    "Comment": "",
    "Defects": "",
    "Elapsed": "",
    "Estimate": "",
    "Forecast": "",
    "In Progress": "",
    "Plan": "Web Regression - 3.22.2-27406 & 3.22.2-27405        (Sprint 32 Release 1)",
    "Plan ID": "R762",
    "Priority": "High",
    "References": "",
    "Run": "Centr",
    "Run Configuration": "",
    "Run ID": "R763",
    "Section": "Regression - Service App",
    "Section Depth": 0,
    "Section Description": "",
    "Status": "Passed",
    "Tested By": "Le Phuong Thao",
    "Tested On": "7/04/2022 2:07 PM",
    "Type": "Other",
    "Version": ""
  }
]

export default centr;